import { useState } from 'react'
import type { FormEvent } from 'react'
import { ChangePasswordPanel } from '../components/ChangePasswordPanel.js'
import { DataSafetyPanel } from '../components/DataSafetyPanel.js'
import { toLocalDate, weekStartOf } from '../lib/date.js'
import type { WeeklyReview } from '../types/index.js'

type ReviewDraft = { wins: string; progress: string; career: string; learning: string; projects: string; problems: string; nextWeek: string; energy: string; focus: string }
type ReviewViewProps = { weeklyReviews: WeeklyReview[]; saveWeeklyReview: (id: string | undefined, body: unknown) => Promise<unknown>; error: string }

const emptyDraft: ReviewDraft = { wins: '', progress: '', career: '', learning: '', projects: '', problems: '', nextWeek: '', energy: '', focus: '' }

export function ReviewView({ weeklyReviews, saveWeeklyReview, error }: ReviewViewProps) {
  const currentWeek = weekStartOf(toLocalDate())
  const existing = weeklyReviews.find((review) => review.weekStart === currentWeek)
  const [draft, setDraft] = useState<ReviewDraft>(() => existing ? { wins: existing.wins, progress: existing.progress, career: existing.career, learning: existing.learning, projects: existing.projects, problems: existing.problems, nextWeek: existing.nextWeek, energy: existing.energy?.toString() ?? '', focus: existing.focus?.toString() ?? '' } : emptyDraft)
  function setField(field: keyof ReviewDraft, value: string) { setDraft((current) => ({ ...current, [field]: value })) }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await saveWeeklyReview(existing?.id, { ...draft, weekStart: currentWeek, energy: draft.energy ? Number(draft.energy) : null, focus: draft.focus ? Number(draft.focus) : null }) }
  const fields: Array<[keyof ReviewDraft, string, string]> = [['wins', 'Wins', 'What went well?'], ['progress', 'Progress', 'Which goals moved?'], ['career', 'Career', 'Applications, responses, interviews, or offers'], ['learning', 'Learning', 'What did you practice or learn?'], ['projects', 'Projects', 'What shipped or moved forward?'], ['problems', 'Problems', 'What blocked you?'], ['nextWeek', 'Next week', 'Choose your top three priorities']]
  return <section className="review-page">{error && <p className="error-banner" role="alert">{error}</p>}<div className="section-heading goals-header"><div><p className="eyebrow">Review</p><h2>Weekly review</h2></div><span className="count-badge">{currentWeek}</span></div><p className="muted growth-intro">Take ten minutes to notice what happened, what changed, and what deserves attention next.</p><form className="review-form" onSubmit={(event) => void submit(event)}>{fields.map(([field, label, placeholder]) => <label key={field}>{label}<textarea onChange={(event) => setField(field, event.target.value)} placeholder={placeholder} value={draft[field]} /></label>)}<div className="review-ratings"><label>Energy<select aria-label="Energy rating" onChange={(event) => setField('energy', event.target.value)} value={draft.energy}><option value="">Not rated</option>{[1, 2, 3, 4, 5].map((rating) => <option key={rating} value={rating}>{rating}/5</option>)}</select></label><label>Focus<select aria-label="Focus rating" onChange={(event) => setField('focus', event.target.value)} value={draft.focus}><option value="">Not rated</option>{[1, 2, 3, 4, 5].map((rating) => <option key={rating} value={rating}>{rating}/5</option>)}</select></label></div><button type="submit">Save weekly review</button></form><div className="review-history"><DataSafetyPanel /><ChangePasswordPanel /></div>{weeklyReviews.length > 1 && <div className="review-history"><p className="eyebrow">History</p><h2>Previous reviews</h2>{weeklyReviews.filter((review) => review.weekStart !== currentWeek).map((review) => <article className="goal-card" key={review.id}><div className="goal-card-header"><h3>{review.weekStart}</h3><span className="status-pill recorded">saved</span></div><p className="goal-why">{review.nextWeek || review.wins || 'No summary added.'}</p></article>)}</div>}</section>
}